package com.challenge.ct.mbs.object;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;
import com.challenge.ct.mbs.utils.Const;

@DynamoDBTable(tableName = Const.TABLE_NAME_ADDRESS)
public class Address {
    private String addressId;

    private String street1;
    private String street2;

    private String unit;
    private String county;

    private String city;
    private String state;
    private String zip;
    private String country;

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = Const.TABLE_ADDRESS_COLUMN.KEY)
    public String getAddressId() {
        return addressId;
    }

    @DynamoDBAttribute(attributeName = Const.TABLE_ADDRESS_COLUMN.STREET)
    public String getStreet1() {
        return street1 == null ? " " : street1;
    }

    @DynamoDBAttribute(attributeName = Const.TABLE_ADDRESS_COLUMN.STREET2)
    public String getStreet2() {
        return street2 == null ? " " : street2;
    }

    @DynamoDBAttribute(attributeName = Const.TABLE_ADDRESS_COLUMN.UNIT)
    public String getUnit() {
        return unit == null ? " " : unit;
    }

    @DynamoDBAttribute(attributeName = Const.TABLE_ADDRESS_COLUMN.COUNTY)
    public String getCounty() {
        return county == null ? " " : county;
    }

    @DynamoDBAttribute(attributeName = Const.TABLE_ADDRESS_COLUMN.CITY)
    public String getCity() {
        return city == null ? " " : city;
    }

    @DynamoDBAttribute(attributeName = Const.TABLE_ADDRESS_COLUMN.STATE)
    public String getState() {
        return state == null ? " " : state;
    }

    @DynamoDBAttribute(attributeName = Const.TABLE_ADDRESS_COLUMN.ZIP)
    public String getZip() {
        return zip == null ? " " : zip;
    }

    @DynamoDBAttribute(attributeName = Const.TABLE_ADDRESS_COLUMN.COUNTRY)
    public String getCountry() {
        return country == null ? " " : country;
    }

    public void setAddressId(String addressId) {
        this.addressId = addressId;
    }

    public void setStreet1(String street1) {
        this.street1 = street1;
    }

    public void setStreet2(String street2) {
        this.street2 = street2;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public void setCounty(String county) {
        this.county = county;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public void setState(String state) {
        this.state = state;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public Address() {
        // for database mapper interface
    }

    private Address(String street1, String street2, String unit, String county,
                    String city, String state, String zip, String country) {
        this.street1 = street1;
        this.street2 = street2;
        this.unit = unit;
        this.county = county;
        this.city = city;
        this.state = state;
        this.zip = zip;
        this.country = country;
    }

    public static class Builder {
        private String street1;
        private String street2;

        private String unit;
        private String county;

        private String city;
        private String state;
        private String zip;
        private String country;

        public Builder setStreet1(String street1) {
            this.street1 = street1;
            return this;
        }

        public Builder setStreet2(String street2) {
            this.street2 = street2;
            return this;
        }

        public Builder setUnit(String unit) {
            this.unit = unit;
            return this;
        }

        public Builder setCounty(String county) {
            this.county = county;
            return this;
        }

        public Builder setCity(String city) {
            this.city = city;
            return this;
        }

        public Builder setState(String state) {
            this.state = state;
            return this;
        }

        public Builder setZip(String zip) {
            this.zip = zip;
            return this;
        }

        public Builder setCountry(String country) {
            this.country = country;
            return this;
        }

        public Address build() {
            return new Address(street1, street2, unit, county, city, state, zip, country);
        }
    }
}
