package com.challenge.ct.mbs.object;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;
import com.challenge.ct.mbs.utils.Const;

@DynamoDBTable(tableName = Const.TABLE_NAME_USER)
public class User {
    private String userId;
    private String firstName;
    private String lastName;
    private String phone;
    private String email;
    private String addressId;

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = Const.TABLE_USER_COLUMN.KEY)
    public String getUserId() {
        return userId;
    }

    @DynamoDBAttribute(attributeName = Const.TABLE_USER_COLUMN.FIRST_NAME)
    public String getFirstName() {
        return firstName == null ? "" : firstName;
    }

    @DynamoDBAttribute(attributeName = Const.TABLE_USER_COLUMN.LAST_NAME)
    public String getLastName() {
        return lastName == null ? "" : lastName;
    }

    @DynamoDBAttribute(attributeName = Const.TABLE_USER_COLUMN.PHONE)
    public String getPhone() {
        return phone == null ? "" : phone;
    }

    @DynamoDBAttribute(attributeName = Const.TABLE_USER_COLUMN.EMAIL)
    public String getEmail() {
        return email == null ? "" : email;
    }

    @DynamoDBAttribute(attributeName = Const.TABLE_USER_COLUMN.ADDRESS_ID)
    public String getAddressId() {
        return addressId;
    }

    public User() {

    }

    private User(String firstName, String lastName, String phone, String email, String addressId) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.phone = phone;
        this.email = email;
        this.addressId = addressId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setAddressId(String addressId) {
        this.addressId = addressId;
    }

    public static class Builder {
        private String firstName;
        private String lastName;
        private String phone;
        private String email;
        private String addressId;

        public Builder setFirstName(String firstName) {
            this.firstName = firstName;
            return this;
        }

        public Builder setLastName(String lastName) {
            this.lastName = lastName;
            return this;
        }

        public Builder setPhone(String phone) {
            this.phone = phone;
            return this;
        }

        public Builder setEmail(String email) {
            this.email = email;
            return this;
        }

        public Builder setAddressId(String addressId) {
            this.addressId = addressId;
            return this;
        }

        public User build() {
            return new User(firstName, lastName, phone, email, addressId);
        }
    }
}
